# Site
name: "Edwin Takahashi"
title: "Edwin Takahashi"
description: "Photos, code and other musings."
logo: ''
favicon: ''
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: ''

# Authors
authors:
  Edwin:
    name: Edwin
    display_name: Edwin
    gravatar: 
    email: egao@outlook.com
    web: https://edwintakahashi.com
    twitter: https://twitter.com/TakahashiEdwin
    description: ''

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-analytics

# Google Analytics
jekyll_analytics:
  GoogleAnalytics:
    id: UA-179310709-1
    anonymizeIp: false
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
